### ISSUE TITLE
withspace removed for some tags example <u> 

### ISSUE THREAD

**Issue by almare** [searchturbine/phpwee-php-minifier#18]
In my code I used the tag <u> in a <p> container. The result is now that the required whitespaces before and after the <u> tag are removed. Maybe we can add some excluded tags that will not be optimized?

**Comment by o-evin** [comment]
Just in case you are still experiencing in this issue:
1. HtmlMin.php, line 74, replace with the following:
   `
   $divnodes = $xpath->query('//div|//p|//nav|//footer|//article|//script|//hr|//br|//ul|//li');
   `
2. HtmlMin.php, line 87, replace if statement with the following:

`
if($c->nodeType==3){
                                            $skip = ["a","b","i","span","strong","strike","em", "small", "sub", "sup", "ins", "del", "mark"];
                                            if($c->previousSibling != null && in_array(strtolower($c->previousSibling->nodeName), $skip) == false) {
                                                $c->nodeValue = ltrim($c->nodeValue);
                                            }
                                            if($c->nextSibling != null && in_array(strtolower($c->nextSibling->nodeName), $skip) == false) {
                                                $c->nodeValue = rtrim($c->nodeValue);
                                            }
                    }
`

**Comment by almare** [comment]
Thx a lot!! This works great and should be committed
